### ISSUE TITLE
Where did nabaz go?

### ISSUE THREAD

**Issue by bbrks** [haystackoss/haystack#22]
This repo used to be `nabaz-io/nabaz` (I even forked it when I submitted some PRs: https://github.com/bbrks/nabaz) and had a genuinely interesting but very early-stage project here that I was closely following, related to intelligent caching of Go and Python unit tests based on instrumentation to evaluate what tests ran what code and reduce the set of tests being run to only changed code.

Repurposing the repo for haystack (a completely different project) feels disingenuous and is piggybacking off the initial interest you had gained with `nabaz`, which was heavily advertised by yourself in many communities.

E.g: https://www.reddit.com/r/golang/search?q=nabaz-io%2Fnabaz&sort=relevance&t=all 

It seems like you're also heavily advertising haystack, and I wish you the best of luck with it, but it's not something I am interested in at all, and was quite confused as to how I had apparently both contributed and also starred this project.

**Comment by yuvalsteuer** [comment]
:(

Are you interested in a code sample of nabaz? nabaz had 0 users sadly, making it extremely demotivating to work on.

I'm sorry for the confusion, I'll be sure to notify all github users that starred this project.
